### ISSUE TITLE
翌月に切り替えても左サイドのカレンダーが更新されない

### ISSUE THREAD

**Issue by m-hajisan** [frudens/filemaker-fullcalendar#1]
以下の現象がカレンダー表示およびスケジューラー表示どちらでも同様に発生しています。

画面左側カレンダー両サイドにあるボタンで、翌月もしくは前月に表示切り替えした際に、メインのカレンダーは更新されますが、左サイドのカレンダの日付並びが更新されません。（その後、どこかの日付をクリックすると更新されます）

動作の状況は添付のgifアニメ画像を参照してください。
![calendar_not_refresh](https://user-images.githubusercontent.com/86086994/122514678-44c5c800-d047-11eb-8872-69e273527cd7.gif)

検証した環境
1) Mac OS Big Sur (11.2.3)
    FileMaker 19 (19.2.2.234)
2) Windows 10 pro (21H1)
    FileMaker 19 (19.1.3.315)

**Comment by teruhirokomaki** [comment]
@m-hajisan ご丁寧にありがとうございます。
早速、確認・修正したいと思います。

**Comment by teruhirokomaki** [comment]
@m-hajisan 以下のdevelopブランチにて修正しましたので #1 のバグが修正されているかご確認お願いします。
https://github.com/frudens/filemaker-fullcalendar/tree/develop
修正が確認できましたらmergeします。

**Comment by teruhirokomaki** [comment]
@m-hajisan  ご連絡がないので、クローズします。
mergeしますので、またバグが再現されるようでしたら、再度イシュー登録頂けると助かります。

**Comment by m-hajisan** [comment]
@teruhirokomaki 確認遅くなりすみませんでした。
オブジェクトの更新処理追加による修正で、問題無く動作していました。
対応ありがとうございました。
